services:
  kapi-web:
    container_name: kapi-web
    build: .
    image: kapi
    ports:
      - 3000:3000
    working_dir: /app
    depends_on:
      - mongo
    links:
      - mongo
    env_file:
      - .env.local
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017