"use client"

import Head from 'next/head';

import Link from 'next/link';
import React from 'react';
import Button from '@/src/components/Button';
import LoginStatus from '@/src/components/LoginStatus';

export default function Home() {
  return (
    <>
      <Head>
        <title>Project Design Thriving</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={'p-8'}>
        <LoginStatus />

        <h2 className={'mt-4'}>Welcome to Kapi!</h2>

        <Link href={'/dev-pages'}>
          <Button>See Dev Pages</Button>
        </Link>

        <br />

        <Link href={'/Onboarding'}>
          <Button className={'mt-4'}>See Onboarding</Button>
        </Link>
      </main>
    </>
  );
}
