import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { NotificationBubble } from './notificationBubble';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  interface Notifications {
    icon: string; // icon code
    messageHighlight: string; // bolded message
    mainMessage: string; // remaining message
    timestamp: number; // minutes since notification was sent
    partySize: number | undefined; // number of people in party
    maxPartySize: number | undefined; // max number of people for party
  }

  const notifcations: Array<Notifications> = [
    {
      icon: 'mingcute:trophy-fill',
      messageHighlight: 'Wowow you just got a trophy!',
      mainMessage: '',
      timestamp: 25,
      partySize: undefined,
      maxPartySize: undefined,
    },
    {
      icon: 'mdi:thumb-up',
      messageHighlight: '@thisandthat',
      mainMessage: 'from liked your post',
      timestamp: 62,
      partySize: undefined,
      maxPartySize: undefined,
    },
    {
      icon: 'icon-park-solid:game-handle',
      messageHighlight: '@soandso',
      mainMessage: 'joined your game lobby',
      timestamp: 134,
      partySize: 3,
      maxPartySize: 4,
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {notifcations.map(x => (
          <NotificationBubble notification={x} />
        ))}
      </main>
    </>
  );
}
